### ISSUE TITLE
`npm run setup --silent` fails after asking for email

### ISSUE THREAD

**Issue by mjlyons** [kentcdodds/testing-workshop#103]
Environment info:

* node version (node --version): v8.12.0
* npm version (npm --version): 6.4.1
* yarn version (yarn --version): 1.17.0

Problem description:

Running the following fails on the `npm run setup --silent` step immediately after asking for my email:

```
git clone https://github.com/kentcdodds/testing-workshop.git
cd testing-workshop
npm run setup --silent
```
with the error

```
Failed to update files
Error: No files match the pattern: /Users/mike/src/testing-workshop/cypress/e2e/**/*.js
    at glob (/Users/mike/src/testing-workshop/node_modules/replace-in-file/lib/helpers/glob-async.js:27:23)
    at f (/Users/mike/src/testing-workshop/node_modules/once/once.js:25:25)
    at Glob.<anonymous> (/Users/mike/src/testing-workshop/node_modules/glob/glob.js:151:7)
    at emitOne (events.js:116:13)
    at Glob.emit (events.js:211:7)
    at Glob._finish (/Users/mike/src/testing-workshop/node_modules/glob/glob.js:197:8)
    at done (/Users/mike/src/testing-workshop/node_modules/glob/glob.js:182:14)
    at Glob._processGlobStar2 (/Users/mike/src/testing-workshop/node_modules/glob/glob.js:637:12)
    at /Users/mike/src/testing-workshop/node_modules/glob/glob.js:626:10
    at RES (/Users/mike/src/testing-workshop/node_modules/inflight/inflight.js:31:16)
```
Running each of the steps in the troubleshooting section works, but re-running `npm run setup --silent` continues to fail after.

Suggested solution:

I'm not sure  :(

**Comment by kentcdodds** [comment]
I'm guessing you're following along on Frontend Masters. If that's the case, please make sure you're using the correct branch (see the README). Thanks!
