### ISSUE TITLE
Errors in `npm run setup`

### ISSUE THREAD

**Issue by matthewepler** [kentcdodds/testing-workshop#32]
**Environment info:**

- `mongo` version (`mongod --version`): 3.4.5
- `node` version (`node --version`): 8.1.3
- `npm` version (`npm --version`): 5.0.3
- `yarn` version (`yarn --version`): 0.24.6

**Problem description:**

Tried to run `npm run setup` but got errors:

`[split.api.verify] [api.test] [api.test.integration] [dev.api] The script called "test.integration" which runs "jest --config=tests/jest.config.integration.json --coverage" failed with exit code 1 https://github.com/kentcdodds/nps/blob/v5.0.4/other/ERRORS_AND_WARNINGS.md#failed-with-exit-code`  

`[split.api.verify] [api.test] [api.test.integration] The script called "api.test.integration" which runs "echo nps mongo.stop && nps mongo.stop &>/dev/null || true && concurrently --kill-others --success first --prefix "[{name}]" --names dev.mongo.silent,dev.api,api.test.integration "nps dev.mongo.silent" " sleep 2 && cd api && npm start test.integration --silent && cd .. "" failed with exit code 1 https://github.com/kentcdodds/nps/blob/v5.0.5/other/ERRORS_AND_WARNINGS.md#failed-with-exit-code`  

'[split.api.verify] [api.test] The script called "api.test" which runs "node node_modules/concurrently/src/main.js --kill-others-on-fail --prefix-colors "bgBlue.bold,bgMagenta.bold" --prefix "[{name}]" --names "api.test.unit,api.test.integration" 'nps api.test.unit' 'nps api.test.integration'" failed with exit code 1 https://github.com/kentcdodds/nps/blob/v5.0.5/other/ERRORS_AND_WARNINGS.md#failed-with-exit-code`

`[split.api.verify] The script called "split.api.verify" which runs "node node_modules/rimraf/bin.js api-final && split-guide generate --no-clean --templates-dir other/templates/api --exercises-dir node_modules/.tmp/api --exercises-final-dir api && node node_modules/concurrently/src/main.js --kill-others-on-fail --prefix-colors "bgBlue.bold,bgMagenta.bold" --prefix "[{name}]" --names "api.test,api.demo" 'nps api.test' 'nps api.demo' && nps split.api" failed with exit code 1 https://github.com/kentcdodds/nps/blob/v5.0.5/other/ERRORS_AND_WARNINGS.md#failed-with-exit-code`  

`[split.e2e.verify] nps split.e2e.verify exited with code null
The script called "validate" which runs "nps lint && node node_modules/concurrently/src/main.js --kill-others-on-fail --prefix-colors "bgBlue.bold,bgMagenta.bold,bgGreen.bold" --prefix "[{name}]" --names "split.api.verify,split.client.verify,split.e2e.verify" 'nps split.api.verify' 'nps split.client.verify' 'nps split.e2e.verify'" failed with exit code 1 https://github.com/kentcdodds/nps/blob/v5.0.5/other/ERRORS_AND_WARNINGS.md#failed-with-exit-code`  

**Suggested solution:**

Something wrong with my config? Perhaps a PATH issue? No idea, really.
Here is the results of running `echo $PATH`. You'll see I added `/src/local/bin/mongod` which is the result of running `which mongod`.  
`/usr/local/bin/mongod:/Users/matthewepler/.nvm/versions/node/v8.1.3/bin:/Users/matthewepler/go/bin:/Users/matthewepler/.yarn/bin:/usr/local/heroku/bin:/usr/local/bin:/usr/local/sbin:/usr/local/mysql/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/usr/local/MacGPG2/bin:/Applications/Wireshark.app/Contents/MacOS`

**Comment by kentcdodds** [comment]
Hi there :wave:

Did you follow the troubleshooting guide in the README? Also, what you pasted above is just the output indicating that there was a problem, but it doesn't show me what the problem was/where it occurred. I can help you more if you give me all the output. It could be a lot so I recommend you do something like this:

````
<details>

<summary>full output</summary>

```
{paste the output here}
```

</details>
````

**Comment by matthewepler** [comment]
Thank you for pointing out the Troubleshooting link. I had not seen it the first time through. I ran the scripts individually and the one causing the problem is `npm start split.api.verify`. Here is the full output I get from running that script:

```bash
 [~/Desktop/testing-workshop]
 (master) >> npm start split.api.verify

> testing-workshop@1.0.0 start /Users/matthewepler/Desktop/testing-workshop
> nps "split.api.verify"

nps executing: node node_modules/rimraf/bin.js api-final && split-guide generate --no-clean --templates-dir other/templates/api --exercises-dir node_modules/.tmp/api --exercises-final-dir api && node node_modules/concurrently/src/main.js --kill-others-on-fail --prefix-colors "bgBlue.bold,bgMagenta.bold" --prefix "[{name}]" --names "api.test,api.demo" 'nps api.test' 'nps api.demo' && nps split.api
Saved 28 files:
/Users/matthewepler/Desktop/testing-workshop/node_modules/.tmp/api/.eslintrc
/Users/matthewepler/Desktop/testing-workshop/api/.eslintrc
/Users/matthewepler/Desktop/testing-workshop/node_modules/.tmp/api/demo/integration/__tests__/users.js
/Users/matthewepler/Desktop/testing-workshop/api/demo/integration/__tests__/users.js
/Users/matthewepler/Desktop/testing-workshop/node_modules/.tmp/api/demo/unit/__tests__/get-age.js
/Users/matthewepler/Desktop/testing-workshop/api/demo/unit/__tests__/get-age.js
/Users/matthewepler/Desktop/testing-workshop/node_modules/.tmp/api/demo/unit/__tests__/make-me-a-sandwich.js
/Users/matthewepler/Desktop/testing-workshop/api/demo/unit/__tests__/make-me-a-sandwich.js
/Users/matthewepler/Desktop/testing-workshop/node_modules/.tmp/api/demo/unit/__tests__/sum.js
/Users/matthewepler/Desktop/testing-workshop/api/demo/unit/__tests__/sum.js
/Users/matthewepler/Desktop/testing-workshop/node_modules/.tmp/api/demo/unit/get-age.js
/Users/matthewepler/Desktop/testing-workshop/api/demo/unit/get-age.js
/Users/matthewepler/Desktop/testing-workshop/node_modules/.tmp/api/demo/unit/sum.js
/Users/matthewepler/Desktop/testing-workshop/api/demo/unit/sum.js
/Users/matthewepler/Desktop/testing-workshop/node_modules/.tmp/api/src/models/__tests__/user.js
/Users/matthewepler/Desktop/testing-workshop/api/src/models/__tests__/user.js
/Users/matthewepler/Desktop/testing-workshop/node_modules/.tmp/api/src/models/user.js
/Users/matthewepler/Desktop/testing-workshop/api/src/models/user.js
/Users/matthewepler/Desktop/testing-workshop/node_modules/.tmp/api/src/routes/utils/__tests__/arrayify.js
/Users/matthewepler/Desktop/testing-workshop/api/src/routes/utils/__tests__/arrayify.js
/Users/matthewepler/Desktop/testing-workshop/node_modules/.tmp/api/src/routes/utils/__tests__/get-token-from-header.js
/Users/matthewepler/Desktop/testing-workshop/api/src/routes/utils/__tests__/get-token-from-header.js
/Users/matthewepler/Desktop/testing-workshop/node_modules/.tmp/api/src/routes/utils/arrayify.js
/Users/matthewepler/Desktop/testing-workshop/api/src/routes/utils/arrayify.js
/Users/matthewepler/Desktop/testing-workshop/node_modules/.tmp/api/src/routes/utils/get-token-from-header.js
/Users/matthewepler/Desktop/testing-workshop/api/src/routes/utils/get-token-from-header.js
/Users/matthewepler/Desktop/testing-workshop/node_modules/.tmp/api/tests/integration/articles.test.js
/Users/matthewepler/Desktop/testing-workshop/api/tests/integration/articles.test.js[api.test] nps executing: node node_modules/concurrently/src/main.js --kill-others-on-fail --prefix-colors "bgBlue.bold,bgMagenta.bold" --prefix "[{name}]" --names "api.test.unit,api.test.integration" 'nps api.test.unit' 'nps api.test.integration'
[api.demo] nps executing: node node_modules/concurrently/src/main.js --kill-others-on-fail --prefix-colors "bgBlue.bold,bgMagenta.bold" --prefix "[{name}]" --names "api.demo.unit.single,api.demo.integration.single" 'nps api.demo.unit.single' 'nps api.demo.integration.single'
[api.test] [api.test.unit] nps executing: cd api && npm start test.unit --silent && cd ..
[api.demo] [api.demo.unit.single] nps executing: cd api && npm start demo.unit --silent && cd ..
[api.test] [api.test.integration] nps executing: echo nps mongo.stop && nps mongo.stop &>/dev/null || true && concurrently --kill-others --success first --prefix "[{name}]" --names dev.mongo.silent,dev.api,api.test.integration "nps dev.mongo.silent" " sleep 2 && cd api && npm start test.integration --silent && cd .. "
[api.test] [api.test.integration] nps mongo.stop
[api.demo] [api.demo.integration.single] nps executing: cd api && npm start demo.integration --silent && cd ..
[api.demo] [api.demo.unit.single] nps executing: jest --config=demo/unit/jest.config.json
[api.test] [api.test.unit] nps executing: jest --config=tests/jest.config.unit.json --coverage
[api.demo] [api.demo.integration.single] nps executing: jest --config=demo/integration/jest.config.json
[api.test] [api.test.integration] [dev.mongo.silent] nps executing: nps mongo.silent
[api.test] [api.test.integration] [dev.mongo.silent] nps executing: echo nps mongo && nps mongo &>/dev/null
[api.test] [api.test.integration] [dev.mongo.silent] nps mongo
[api.demo] [api.demo.unit.single]  PASS  demo/unit/__tests__/sum.js
[api.demo] [api.demo.unit.single]  PASS  demo/unit/__tests__/make-me-a-sandwich.js
[api.demo] [api.demo.unit.single]  PASS  demo/unit/__tests__/get-age.js
[api.demo] [api.demo.unit.single]
[api.demo] [api.demo.unit.single] Test Suites: 3 passed, 3 total
[api.demo] [api.demo.unit.single] Tests:       8 passed, 8 total
[api.demo] [api.demo.unit.single] Snapshots:   0 total
[api.demo] [api.demo.unit.single] Time:        4.759s
[api.demo] [api.demo.unit.single] Ran all test suites.
[api.demo] [api.demo.unit.single] nps api.demo.unit.single exited with code 0
[api.test] [api.test.integration] [dev.api] nps executing: jest --config=tests/jest.config.integration.json --coverage
[api.test] [api.test.unit]  PASS  src/routes/utils/__tests__/arrayify.js
[api.test] [api.test.unit]  PASS  src/routes/utils/__tests__/get-token-from-header.js
[api.demo] [api.demo.integration.single]  PASS  demo/integration/__tests__/users.js (6.182s)
[api.demo] [api.demo.integration.single]   unauthorized
[api.demo] [api.demo.integration.single]     ✓ can limit the users (40ms)
[api.demo] [api.demo.integration.single]     ✓ can get users with an offset (16ms)
[api.demo] [api.demo.integration.single]     ✓ cannot add a user (33ms)
[api.demo] [api.demo.integration.single]   authorized
[api.demo] [api.demo.integration.single]     ✓ can add a user (13ms)
[api.demo] [api.demo.integration.single]     ✓ can delete a user (25ms)
[api.demo] [api.demo.integration.single]
[api.demo] [api.demo.integration.single] Test Suites: 1 passed, 1 total
[api.demo] [api.demo.integration.single] Tests:       5 passed, 5 total
[api.demo] [api.demo.integration.single] Snapshots:   0 total
[api.demo] [api.demo.integration.single] Time:        7.224s, estimated 17s
[api.demo] [api.demo.integration.single] Ran all test suites.
[api.demo] [api.demo.integration.single] nps api.demo.integration.single exited with code 0
[api.demo] nps api.demo exited with code 0
[api.test] [api.test.unit]  PASS  src/models/__tests__/article.js
[api.test] [api.test.integration] [dev.api] events.js:182
[api.test] [api.test.integration] [dev.api]       throw er; // Unhandled 'error' event
[api.test] [api.test.integration] [dev.api]       ^
[api.test] [api.test.integration] [dev.api]
[api.test] [api.test.integration] [dev.api] Error: listen EADDRINUSE :::3000
[api.test] [api.test.integration] [dev.api]     at Object.exports._errnoException (util.js:1022:11)
[api.test] [api.test.integration] [dev.api]     at exports._exceptionWithHostPort (util.js:1045:20)
[api.test] [api.test.integration] [dev.api]     at Server.setupListenHandle [as _listen2] (net.js:1315:14)
[api.test] [api.test.integration] [dev.api]     at listenInCluster (net.js:1363:12)
[api.test] [api.test.integration] [dev.api]     at Server.listen (net.js:1463:7)
[api.test] [api.test.integration] [dev.api]     at Function.listen (/Users/matthewepler/Desktop/testing-workshop/api/node_modules/express/lib/application.js:618:24)
[api.test] [api.test.integration] [dev.api]     at /Users/matthewepler/Desktop/testing-workshop/api/src/start-server.js:96:77
[api.test] [api.test.integration] [dev.api]     at Promise (<anonymous>)
[api.test] [api.test.integration] [dev.api]     at /Users/matthewepler/Desktop/testing-workshop/api/src/start-server.js:95:61
[api.test] [api.test.integration] [dev.api]     at Generator.next (<anonymous>)
[api.test] [api.test.integration] [dev.api] The script called "test.integration" which runs "jest --config=tests/jest.config.integration.json --coverage" failed with exit code 1 https://github.com/kentcdodds/nps/blob/v5.0.4/other/ERRORS_AND_WARNINGS.md#failed-with-exit-code
[api.test] [api.test.integration] [dev.api]  sleep 2 && cd api && npm start test.integration --silent && cd ..  exited with code 1
[api.test] [api.test.integration] --> Sending SIGTERM to other processes..
[api.test] [api.test.integration] [dev.mongo.silent] nps dev.mongo.silent exited with code null
[api.test] [api.test.integration] The script called "api.test.integration" which runs "echo nps mongo.stop && nps mongo.stop &>/dev/null || true && concurrently --kill-others --success first --prefix "[{name}]" --names dev.mongo.silent,dev.api,api.test.integration "nps dev.mongo.silent" " sleep 2 && cd api && npm start test.integration --silent && cd .. "" failed with exit code 1 https://github.com/kentcdodds/nps/blob/v5.0.5/other/ERRORS_AND_WARNINGS.md#failed-with-exit-code
[api.test] [api.test.integration] nps api.test.integration exited with code 1
[api.test] --> Sending SIGTERM to other processes..
[api.test] [api.test.unit] nps api.test.unit exited with code null
[api.test] The script called "api.test" which runs "node node_modules/concurrently/src/main.js --kill-others-on-fail --prefix-colors "bgBlue.bold,bgMagenta.bold" --prefix "[{name}]" --names "api.test.unit,api.test.integration" 'nps api.test.unit' 'nps api.test.integration'" failed with exit code 1 https://github.com/kentcdodds/nps/blob/v5.0.5/other/ERRORS_AND_WARNINGS.md#failed-with-exit-code
[api.test] nps api.test exited with code 1
The script called "split.api.verify" which runs "node node_modules/rimraf/bin.js api-final && split-guide generate --no-clean --templates-dir other/templates/api --exercises-dir node_modules/.tmp/api --exercises-final-dir api && node node_modules/concurrently/src/main.js --kill-others-on-fail --prefix-colors "bgBlue.bold,bgMagenta.bold" --prefix "[{name}]" --names "api.test,api.demo" 'nps api.test' 'nps api.demo' && nps split.api" failed with exit code 1 https://github.com/kentcdodds/nps/blob/v5.0.5/other/ERRORS_AND_WARNINGS.md#failed-with-exit-code
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! testing-workshop@1.0.0 start: `nps "split.api.verify"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the testing-workshop@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/matthewepler/.npm/_logs/2017-07-07T21_19_08_693Z-debug.log
```

**Comment by matthewepler** [comment]
AH! I saw the error. It was because I had another server running on port 3000. I shut down that server and rand the script again and it passed fine. 

Thanks for the quick response and your time.

**Comment by kentcdodds** [comment]
Glad you got it worked out :smile:
