### ISSUE TITLE
Error: Cannot find module './other/db-db-test-utils'

### ISSUE THREAD

**Issue by delateurj** [kentcdodds/testing-workshop#46]
Environment info:
Max OS

* `node` version (`node --version`): 8.4.0
* `npm` version (`npm --version`): 5.6.0
* `yarn` version (`yarn --version`): 1.3.2

Problem description:

On both npm run dev from project folder or npm run dev from server folder I get the following error message.  (Also get if I run the command as sudo):

oes-iMac:testing-workshop joe$ npm run dev

> testing-workshop@2.0.0 dev /Users/joe/Dropbox/Programming/testing-workshop
> as-a DEV concurrently --names "server,client" --prefix "[{name}]" --prefix-colors "bgCyan.reset.bold,bgGreen.reset.bold" "npm run dev:server --silent" "npm run dev:client --silent"

[server] module.js:491
[server]     throw err;
[server]     ^
[server]
[server] Error: Cannot find module './other/db-db-test-utils'
[server]     at Function.Module._resolveFilename (module.js:489:15)
[server]     at Function.Module._load (module.js:439:25)
[server]     at Module.require (module.js:517:17)
[server]     at require (internal/module.js:11:18)
[server]     at Object.<anonymous> (/Users/joe/Dropbox/Programming/testing-workshop/server/dev.js:2:1)
[server]     at Module._compile (module.js:573:30)
[server]     at Object.Module._extensions..js (module.js:584:10)
[server]     at Module.load (module.js:507:32)
[server]     at tryModuleLoad (module.js:470:12)
[server]     at Function.Module._load (module.js:462:3)

Searched for the *db-db-test-utils* on mac and did not find anything.

Deleted node_modules under server and did a npm install and the same error occurred on npm run dev.

Thanks,
Joe.

**Comment by delateurj** [comment]
dev.js in testing-workshop/server had the following:

require('babel-register')
require('./other/db-db-test-utils').initDb()
require('./src')

I changed require('./other/db-db-test-utils').initDb() to:
require('./other/db-test-utils').initDb()
removing the seemingly extra "db-"

This eliminated the error...however, I now get unexpected token error from the generateUserData function...see below:

npm run dev

> testing-workshop@2.0.0 dev /Users/joe/Dropbox/Programming/testing-workshop
> as-a DEV concurrently --names "server,client" --prefix "[{name}]" --prefix-colors "bgCyan.reset.bold,bgGreen.reset.bold" "npm run dev:server --silent" "npm run dev:client --silent"

[server] /Users/joe/Dropbox/Programming/testing-workshop/server/node_modules/babel-core/lib/transformation/file/index.js:590
[server]       throw err;
[server]       ^
[server]
[server] SyntaxError: /Users/joe/Dropbox/Programming/testing-workshop/other/generate.js: Unexpected token (9:2)
[server]    7 | function generateUserData({
[server]    8 |   password = faker.internet.password(),
[server] >  9 |   ...overrides
[server]      |   ^
[server]   10 |  } = {}) {
[server]   11 |   return {
[server]   12 |     username: faker.internet.userName(),
[server]     at Parser.pp$5.raise (/Users/joe/Dropbox/Programming/testing-workshop/server/node_modules/babylon/lib/index.js:4454:13)
[server]     at Parser.pp.unexpected (/Users/joe/Dropbox/Programming/testing-workshop/server/node_modules/babylon/lib/index.js:1761:8)
[server]     at Parser.pp$3.parseIdentifier (/Users/joe/Dropbox/Programming/testing-workshop/server/node_modules/babylon/lib/index.js:4332:10)
[server]     at Parser.pp$3.parsePropertyName (/Users/joe/Dropbox/Programming/testing-workshop/server/node_modules/babylon/lib/index.js:4156:96)
[server]     at Parser.pp$3.parseObj (/Users/joe/Dropbox/Programming/testing-workshop/server/node_modules/babylon/lib/index.js:4045:12)
[server]     at Parser.pp$2.parseBindingAtom (/Users/joe/Dropbox/Programming/testing-workshop/server/node_modules/babylon/lib/index.js:3087:19)
[server]     at Parser.pp$2.parseMaybeDefault (/Users/joe/Dropbox/Programming/testing-workshop/server/node_modules/babylon/lib/index.js:3136:23)
[server]     at Parser.pp$2.parseBindingList (/Users/joe/Dropbox/Programming/testing-workshop/server/node_modules/babylon/lib/index.js:3116:23)
[server]     at Parser.pp$1.parseFunctionParams (/Users/joe/Dropbox/Programming/testing-workshop/server/node_modules/babylon/lib/index.js:2395:22)
[server]     at Parser.pp$1.parseFunction (/Users/joe/Dropbox/Programming/testing-workshop/server/node_modules/babylon/lib/index.js:2385:8)
[client] Starting the development server...
[client]
[client] Compiled successfully!
[client]
[client] You can now view client in the browser.
[client]
[client]   Local:            http://localhost:3000/
[client]   On Your Network:  http://192.168.1.165:3000/
[client]
[client] Note that the development build is not optimized.
[client] To create a production build, use npm run build.
[client]

**Comment by delateurj** [comment]
I noticed that the top of the file has the following comment:
// this file is not transpiled
// we could probably make it work
// but meh... ¯\_(ツ)_/¯
const faker = require('faker')
const { getSaltAndHash } = require('../server/src/auth')

function generateUserData({
  password = faker.internet.password(),
  ...overrides
 } = {}) {
  return {
    username: faker.internet.userName(),
    ...getSaltAndHash(password),
    ...overrides,
  }
}

**Comment by delateurj** [comment]
Just noticed the comment about the fem branch in the readme...blew everything away...cloned a repo again...switched to fem branch and going through setup...will let you know if this branch works...

**Comment by delateurj** [comment]
Up and running on the fem branch...so I will close but pretty sure the db-db-test-utils require in dev.js is a bug in current version.  And while relatively new to javascript...I think the spread operator in a non transpiled file is an issue in the new version.
