### ISSUE TITLE
Windows : Auth test fail due to Cypress timing out

### ISSUE THREAD

**Issue by stefanivic** [kentcdodds/testing-workshop#52]
Environment info:

* `Operating system` : Windows 10 Pro, Version 1709, OS Build : 16299.192.
* `Windows insiders` : No. Running on stable builds.
* `node` version (`node --version`): v8.9.4
* `npm` version (`npm --version`): v5.6.0
* `yarn` version (`yarn --version`): v1.3.2

Problem description:

Reference #49

```
[test:e2e]   authentication
    1) should allow users to register
    2) should allow existing users to login
[test:e2e]
[test:e2e]   authentication
    3) should allow existing users to login
[test:e2e]
[test:e2e]
[test:e2e]   0 passing (10s)
[test:e2e]   3 failing
[test:e2e]
[test:e2e]   1) authentication should allow users to register:
[test:e2e]      CypressError: Timed out retrying: expected 'http://localhost:8001/' to equal 'http://localhost:8001\r/'
[test:e2e]       at Object.cypressErr (http://localhost:8001/__cypress/runner/cypress_runner.js:65969:11)
[test:e2e]       at Object.throwErr (http://localhost:8001/__cypress/runner/cypress_runner.js:65934:18)
[test:e2e]       at Object.throwErrByPath (http://localhost:8001/__cypress/runner/cypress_runner.js:65961:17)
[test:e2e]       at retry (http://localhost:8001/__cypress/runner/cypress_runner.js:60073:16)
[test:e2e]       at http://localhost:8001/__cypress/runner/cypress_runner.js:52591:18
[test:e2e]       at tryCatcher (http://localhost:8001/__cypress/runner/cypress_runner.js:6268:23)
[test:e2e]       at Promise._settlePromiseFromHandler (http://localhost:8001/__cypress/runner/cypress_runner.js:4290:31)
[test:e2e]       at Promise._settlePromise (http://localhost:8001/__cypress/runner/cypress_runner.js:4347:18)
[test:e2e]       at Promise._settlePromise0 (http://localhost:8001/__cypress/runner/cypress_runner.js:4392:10)
[test:e2e]       at Promise._settlePromises (http://localhost:8001/__cypress/runner/cypress_runner.js:4467:18)
[test:e2e]       at Async._drainQueue (http://localhost:8001/__cypress/runner/cypress_runner.js:1200:16)
[test:e2e]       at Async._drainQueues (http://localhost:8001/__cypress/runner/cypress_runner.js:1210:10)
[test:e2e]       at Async.drainQueues (http://localhost:8001/__cypress/runner/cypress_runner.js:1084:14)
[test:e2e]
[test:e2e]   2) authentication should allow existing users to login:
[test:e2e]      CypressError: cy.request() failed on:
[test:e2e]
/auth/registerp://localhost:3001/api
[test:e2e]
[test:e2e] The response we received from your web server was:
[test:e2e]
[test:e2e]   > 404: Not Found
[test:e2e]
[test:e2e] This was considered a failure because the status code was not '2xx' or '3xx'.
[test:e2e]
[test:e2e] If you do not want status codes to cause failures pass the option: 'failOnStatusCode: false'
[test:e2e]
[test:e2e] -----------------------------------------------------------
[test:e2e]
[test:e2e] The request we sent was:
[test:e2e]
[test:e2e] Method: POST
/auth/register: http://localhost:3001/api
[test:e2e] Headers: {
[test:e2e]   "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Cypress/1.4.1 Chrome/53.0.2785.143 Electron/1.4.6 Safari/537.36",
[test:e2e]   "accept": "*/*",
[test:e2e]   "accept-encoding": "gzip, deflate",
[test:e2e]   "content-type": "application/json",
[test:e2e]   "content-length": 55
[test:e2e] }
[test:e2e] Body: {"username":"Alexis_Koch","password":"YbJ_u0zGHqQECin"}
[test:e2e]
[test:e2e] -----------------------------------------------------------
[test:e2e]
[test:e2e] The response we got was:
[test:e2e]
[test:e2e] Status: 404 - Not Found
[test:e2e] Headers: {
[test:e2e]   "x-powered-by": "Express",
[test:e2e]   "access-control-allow-origin": "*",
[test:e2e]   "content-security-policy": "default-src 'self'",
[test:e2e]   "x-content-type-options": "nosniff",
[test:e2e]   "content-type": "text/html; charset=utf-8",
[test:e2e]   "content-length": "160",
[test:e2e]   "date": "Fri, 02 Feb 2018 14:59:25 GMT",
[test:e2e]   "connection": "close"
[test:e2e] }
[test:e2e] Body: <!DOCTYPE html>
[test:e2e] <html lang="en">
[test:e2e] <head>
[test:e2e] <meta charset="utf-8">
[test:e2e] <title>Error</title>
[test:e2e] </head>
[test:e2e] <body...
[test:e2e]
[test:e2e]       at Object.cypressErr (http://localhost:8001/__cypress/runner/cypress_runner.js:65969:11)
[test:e2e]       at Object.throwErr (http://localhost:8001/__cypress/runner/cypress_runner.js:65934:18)
[test:e2e]       at Object.throwErrByPath (http://localhost:8001/__cypress/runner/cypress_runner.js:65961:17)
[test:e2e]       at http://localhost:8001/__cypress/runner/cypress_runner.js:58366:20
[test:e2e]       at tryCatcher (http://localhost:8001/__cypress/runner/cypress_runner.js:6268:23)
[test:e2e]       at Promise._settlePromiseFromHandler (http://localhost:8001/__cypress/runner/cypress_runner.js:4290:31)
[test:e2e]       at Promise._settlePromise (http://localhost:8001/__cypress/runner/cypress_runner.js:4347:18)
[test:e2e]       at Promise._settlePromise0 (http://localhost:8001/__cypress/runner/cypress_runner.js:4392:10)
[test:e2e]       at Promise._settlePromises (http://localhost:8001/__cypress/runner/cypress_runner.js:4471:18)
[test:e2e]       at Async._drainQueue (http://localhost:8001/__cypress/runner/cypress_runner.js:1200:16)
[test:e2e]       at Async._drainQueues (http://localhost:8001/__cypress/runner/cypress_runner.js:1210:10)
[test:e2e]       at Async.drainQueues (http://localhost:8001/__cypress/runner/cypress_runner.js:1084:14)
[test:e2e]
[test:e2e]   3) authentication should allow existing users to login:
[test:e2e]      CypressError: cy.request() failed on:
[test:e2e]
/auth/registerp://localhost:3001/api
[test:e2e]
[test:e2e] The response we received from your web server was:
[test:e2e]
[test:e2e]   > 404: Not Found
[test:e2e]
[test:e2e] This was considered a failure because the status code was not '2xx' or '3xx'.
[test:e2e]
[test:e2e] If you do not want status codes to cause failures pass the option: 'failOnStatusCode: false'
[test:e2e]
[test:e2e] -----------------------------------------------------------
[test:e2e]
[test:e2e] The request we sent was:
[test:e2e]
[test:e2e] Method: POST
/auth/register: http://localhost:3001/api
[test:e2e] Headers: {
[test:e2e]   "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Cypress/1.4.1 Chrome/53.0.2785.143 Electron/1.4.6 Safari/537.36",
[test:e2e]   "accept": "*/*",
[test:e2e]   "accept-encoding": "gzip, deflate",
[test:e2e]   "content-type": "application/json",
[test:e2e]   "content-length": 58
[test:e2e] }
[test:e2e] Body: {"username":"Darren_Volkman","password":"LBvfwpIOwrmhm8L"}
[test:e2e]
[test:e2e] -----------------------------------------------------------
[test:e2e]
[test:e2e] The response we got was:
[test:e2e]
[test:e2e] Status: 404 - Not Found
[test:e2e] Headers: {
[test:e2e]   "x-powered-by": "Express",
[test:e2e]   "access-control-allow-origin": "*",
[test:e2e]   "content-security-policy": "default-src 'self'",
[test:e2e]   "x-content-type-options": "nosniff",
[test:e2e]   "content-type": "text/html; charset=utf-8",
[test:e2e]   "content-length": "160",
[test:e2e]   "date": "Fri, 02 Feb 2018 14:59:26 GMT",
[test:e2e]   "connection": "close"
[test:e2e] }
[test:e2e] Body: <!DOCTYPE html>
[test:e2e] <html lang="en">
[test:e2e] <head>
[test:e2e] <meta charset="utf-8">
[test:e2e] <title>Error</title>
[test:e2e] </head>
[test:e2e] <body...
[test:e2e]
[test:e2e]       at Object.cypressErr (http://localhost:8001/__cypress/runner/cypress_runner.js:65969:11)
[test:e2e]       at Object.throwErr (http://localhost:8001/__cypress/runner/cypress_runner.js:65934:18)
[test:e2e]       at Object.throwErrByPath (http://localhost:8001/__cypress/runner/cypress_runner.js:65961:17)
[test:e2e]       at http://localhost:8001/__cypress/runner/cypress_runner.js:58366:20
[test:e2e]       at tryCatcher (http://localhost:8001/__cypress/runner/cypress_runner.js:6268:23)
[test:e2e]       at Promise._settlePromiseFromHandler (http://localhost:8001/__cypress/runner/cypress_runner.js:4290:31)
[test:e2e]       at Promise._settlePromise (http://localhost:8001/__cypress/runner/cypress_runner.js:4347:18)
[test:e2e]       at Promise._settlePromise0 (http://localhost:8001/__cypress/runner/cypress_runner.js:4392:10)
[test:e2e]       at Promise._settlePromises (http://localhost:8001/__cypress/runner/cypress_runner.js:4471:18)
[test:e2e]       at Async._drainQueue (http://localhost:8001/__cypress/runner/cypress_runner.js:1200:16)
[test:e2e]       at Async._drainQueues (http://localhost:8001/__cypress/runner/cypress_runner.js:1210:10)
[test:e2e]       at Async.drainQueues (http://localhost:8001/__cypress/runner/cypress_runner.js:1084:14)
[test:e2e]
[test:e2e]
[test:e2e]
[test:e2e]
[test:e2e]   (Tests Finished)
[test:e2e]
[test:e2e]   - Tests:           3
[test:e2e]   - Passes:          0
[test:e2e]   - Failures:        3
[test:e2e]   - Pending:         0
[test:e2e]   - Duration:        9 seconds
[test:e2e]   - Screenshots:     3
[test:e2e]   - Video Recorded:  true
[test:e2e]   - Cypress Version: 1.4.1
[test:e2e]
[test:e2e]
[test:e2e]   (Screenshots)
[test:e2e]
[test:e2e]   - C:\Users\night\Development\testing-workshop\cypress\screenshots\authentication -- should allow users to register.png (1280x720)
[test:e2e]   - C:\Users\night\Development\testing-workshop\cypress\screenshots\authentication -- should allow existing users to login.png (1280x720)
[test:e2e]   - C:\Users\night\Development\testing-workshop\cypress\screenshots\authentication -- should allow existing users to login.png (1280x720)
[test:e2e]
[test:e2e]
[test:e2e]   (Video)
[test:e2e]
[test:e2e]   - Started processing:   Compressing to 32 CRF
[test:e2e]   - Finished processing:  C:\Users\night\Development\testing-workshop\cypress\videos\kjt42.mp4 (8 seconds)
[test:e2e]
[test:e2e]
[test:e2e]   (All Done)
[test:e2e]
[test:e2e] npm-run-all exit code 1
[test:e2e] Error: npm-run-all exit code 1
[test:e2e]     at ChildProcess.proc.on (C:\Users\night\Development\testing-workshop\node_modules\as-a\src\run-command.js:38:23)
[test:e2e]     at emitTwo (events.js:126:13)
[test:e2e]     at ChildProcess.emit (events.js:214:7)
[test:e2e]     at ChildProcess.cp.emit (C:\Users\night\Development\testing-workshop\node_modules\as-a\node_modules\cross-spawn\lib\enoent.js:40:29)
[test:e2e]     at maybeClose (internal/child_process.js:925:16)
[test:e2e]     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
[test:e2e] npm run test:e2e:run --silent exited with code 4294967295
```

Suggested solution:

**Comment by bodiddlie** [comment]
Can verify the same on my machine with the same versions/setup. One thing I'm getting not mentioned here is an error dialog like this:
![image](https://user-images.githubusercontent.com/2413413/35741029-f0e4327c-07f3-11e8-9152-24f6937352a5.png)

This pops up shortly after the console starts `cypress open`. There are no errors logged in the console output, and I'm not seeing any logged elsewhere either. The Cypress window opens up after that and then the tests fail when the api call to register a user returns a 404 like above.

**Comment by kentcdodds** [comment]
Perfect! Thank you @stefanivic! This is exactly the kind of feedback I need. Thanks! I'll look into getting this fixed :D

**Comment by kentcdodds** [comment]
Also, if anyone else would like to do some digging and figure out what's going on please be my guest!

**Comment by kentcdodds** [comment]
I _think_ I may have fixed it. Could you try again?

Here's what I had to do: https://github.com/kentcdodds/testing-workshop/commit/9ac56ff0ef82b14bcc1cb300b137bb372afe318f

cc @bahmutov, you might be interested in this. I think it's probably a bug in Cypress related to `Cypress.env`.

**Comment by bodiddlie** [comment]
The tests pass now. The error dialog I noted above still is there, but it doesn't seem to be affecting the tests.

**Comment by kentcdodds** [comment]
Thanks for verifying things @bodiddlie! @stefanivic, could you run `npm run test:e2e` (runs e2e tests in dev mode) and see if you get the same dialog?

If so, then I think there's probably something wrong in the way I'm configuring Cypress, or Cypress has a bug. @bahmutov, I think that there is indeed a bug with `Cypress.env` on windows (includes a newline character at the end of variables), and there may be a bug related to this popup dialog that @bodiddlie mentions in a comment above.

Thanks everyone!

**Comment by rigobauer** [comment]
I still have this problem.

Macbook Pro with 10.11.6 (El Capitan)
* `node` version (`node --version`): 8.9.4
* `npm` version (`npm --version`): 5.6.0
* `yarn` version (`yarn --version`): 1.3.2

So like in the issue statement, I get... 

```
1) authentication should allow existing users to login:
     CypressError: Timed out retrying: expected 'http://localhost:8001/login' to equal 'http://localhost:8001/'
      at Object.cypressErr (http://localhost:8001/__cypress/runner/cypress_runner.js:65859:11)
      at Object.throwErr (http://localhost:8001/__cypress/runner/cypress_runner.js:65824:18)
      at Object.throwErrByPath (http://localhost:8001/__cypress/runner/cypress_runner.js:65851:17)
      at retry (http://localhost:8001/__cypress/runner/cypress_runner.js:59963:16)
      at http://localhost:8001/__cypress/runner/cypress_runner.js:52481:18
      at tryCatcher (http://localhost:8001/__cypress/runner/cypress_runner.js:6268:23)
      at Promise._settlePromiseFromHandler (http://localhost:8001/__cypress/runner/cypress_runner.js:4290:31)
      at Promise._settlePromise (http://localhost:8001/__cypress/runner/cypress_runner.js:4347:18)
      at Promise._settlePromise0 (http://localhost:8001/__cypress/runner/cypress_runner.js:4392:10)
      at Promise._settlePromises (http://localhost:8001/__cypress/runner/cypress_runner.js:4467:18)
      at Async._drainQueue (http://localhost:8001/__cypress/runner/cypress_runner.js:1200:16)
      at Async._drainQueues (http://localhost:8001/__cypress/runner/cypress_runner.js:1210:10)
      at Async.drainQueues (http://localhost:8001/__cypress/runner/cypress_runner.js:1084:14)
```

But after that, things get more "funky"...

```
(Video)

  - Started processing:   Compressing to 32 CRF
  - Finished processing:  /Users/aiglesias/Coding/react/testing-workshop/cypress/videos/kjkln.mp4 (26 seconds)


  (All Done)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! testing-workshop@2.0.0 cy:run: `cypress run`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the testing-workshop@2.0.0 cy:run script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/aiglesias/.npm/_logs/2018-02-02T17_24_23_397Z-debug.log
[server] npm run start:server --silent exited with code null
[client] npm run start:client --silent exited with code null
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! testing-workshop@2.0.0 start:core: `concurrently --names "server,client" --prefix "[{name}]" --prefix-colors "bgCyan.reset.bold,bgGreen.reset.bold" "npm run start:server --silent" "npm run start:client --silent"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the testing-workshop@2.0.0 start:core script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/aiglesias/.npm/_logs/2018-02-02T17_24_23_738Z-debug.log
ERROR: "cy:run" exited with 1.
npm-run-all exit code 1
Error: npm-run-all exit code 1
    at ChildProcess.proc.on (/Users/aiglesias/Coding/react/testing-workshop/node_modules/as-a/src/run-command.js:38:23)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 255
npm ERR! testing-workshop@2.0.0 test:e2e:run: `as-a E2E npm-run-all --parallel --race start:core cy:run`
npm ERR! Exit status 255
npm ERR!
npm ERR! Failed at the testing-workshop@2.0.0 test:e2e:run script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/aiglesias/.npm/_logs/2018-02-02T17_24_23_841Z-debug.log
```

Let me know if you need me to try something...

**Comment by kentcdodds** [comment]
Thanks for sharing @rigobauer. I think this is a different issue. Could you file a new issue and paste _all_ the output of the command `npm run test:e2e:run` (I know it'll be quite a bit). Thanks!

**Comment by rigobauer** [comment]
Sure! Going for it!

**Comment by stefanivic** [comment]
@kentcdodds works fine for me now. :D
