### ISSUE TITLE
Tests not running, because babel could find "es2015" preset

### ISSUE THREAD

**Issue by Shermayster** [kentcdodds/testing-workshop#86]
Environment info:

* `node` version (`node --version`): 8.11.3
* `npm` version (`npm --version`): 6.4.1
* `yarn` version (`yarn --version`): 1.9.4

Problem description:
When I try to run tests in the client directory, I get the following error:

● Test suite failed to run

    Couldn't find preset "es2015" relative to directory "/Users/pavelshermayster"

      at ../node_modules/babel-core/lib/transformation/file/options/option-manager.js:293:19
          at Array.map (<anonymous>)
      at OptionManager.resolvePresets (../node_modules/babel-core/lib/transformation/file/options/option-manager.js:275:20)
      at OptionManager.mergePresets (../node_modules/babel-core/lib/transformation/file/options/option-manager.js:264:10)
      at OptionManager.mergeOptions (../node_modules/babel-core/lib/transformation/file/options/option-manager.js:249:14)
      at OptionManager.init (../node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
      at File.initOptions (../node_modules/babel-core/lib/transformation/file/index.js:212:65)
      at new File (../node_modules/babel-core/lib/transformation/file/index.js:135:24)
      at Pipeline.transform (../node_modules/babel-core/lib/transformation/pipeline.js:46:16)

**Comment by Shermayster** [comment]
I updated all my global npm packages, and now it's working properly
You can close the issue
