### ISSUE TITLE
Today I Learned client - cannot load initial data

### ISSUE THREAD

**Issue by iwakoscott** [kentcdodds/testing-workshop#92]
Environment info:

* `node` version (`node --version`): v10.13.0
* `npm` version (`npm --version`): 6.4.1
* `yarn` version (`yarn --version`): 1.9.4

Problem description:

I was trying to get the "Today I Learned" client to run on my machine, however,  I ran into a couple of issues which I am not sure are related.  When I run `npm run dev` inside of my `/client` the development server opens up but, I do not see any randomly generated posts.

<img width="1280" alt="screen shot 2018-12-05 at 11 08 52 pm" src="https://user-images.githubusercontent.com/13685868/49567522-da166c00-f8e2-11e8-92b5-aab73d46566a.png">

Here is what I am seeing in the console - 

<img width="852" alt="screen shot 2018-12-05 at 11 11 03 pm" src="https://user-images.githubusercontent.com/13685868/49567602-15189f80-f8e3-11e8-8626-6f630afb262e.png">

I ran the `npm run setup --silent` and everything looks great until the E2E script. I am getting the following error - 
```
{ Error: Command failed: npm run cy:run
[test:e2e]     at makeError (/Users/ssiwako/Documents/frontend-masters/testing-workshop/node_modules/start-server-and-test/node_modules/execa/index.js:174:9)
[test:e2e]     at Promise.all.then.arr (/Users/ssiwako/Documents/frontend-masters/testing-workshop/node_modules/start-server-and-test/node_modules/execa/index.js:278:16)
[test:e2e]     at <anonymous>
[test:e2e]     at process._tickCallback (internal/process/next_tick.js:189:7)
[test:e2e]   code: 1,
[test:e2e]   stdout: null,
[test:e2e]   stderr: null,
[test:e2e]   failed: true,
[test:e2e]   signal: null,
[test:e2e]   cmd: 'npm run cy:run',
[test:e2e]   timedOut: false,
[test:e2e]   killed: false }
[test:e2e] start-server-and-test exit code 1
[test:e2e] Error: start-server-and-test exit code 1
[test:e2e]     at ChildProcess.proc.on (/Users/ssiwako/Documents/frontend-masters/testing-workshop/node_modules/as-a/src/run-command.js:38:23)
[test:e2e]     at emitTwo (events.js:126:13)
[test:e2e]     at ChildProcess.emit (events.js:214:7)
[test:e2e]     at maybeClose (internal/child_process.js:915:16)
[test:e2e]     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
[test:e2e] [client] 
[test:e2e] [client] INFO: Gracefully shutting down. Please wait...
[test:e2e] [server] npm run start:server --silent exited with code 0
[test:e2e] [client] npm run start:client --silent exited with code 0
[test:e2e] npm run test:e2e:run --silent exited with code 255
```
 As aforementioned, I am not sure if this is the reason why the "Today I Learned"  client isn't working.

**Comment by kentcdodds** [comment]
I'm sorry, I'm not sure what's going on there. I'm also not able to reproduce the error you're seeing. If I run:

```
git clone https://github.com/kentcdodds/testing-workshop.git
cd testing-workshop
npm run setup
```

Here's what I see:

```
~/Desktop
😼  $ git clone https://github.com/kentcdodds/testing-workshop.git
Cloning into 'testing-workshop'...
npm ruremote: Enumerating objects: 19, done.
remote: Counting objects: 100% (19/19), done.
remote: Compressing objects: 100% (19/19), done.
'upReceiving objects:  67% (3133/4675), 1.46 MiB | 2.58 MiB/s   
remote: Total 4675 (delta 2), reused 7 (delta 0), pack-reused 4656
Receiving objects: 100% (4675/4675), 3.89 MiB | 4.07 MiB/s, done.
Resolving deltas: 100% (2578/2578), done.
~/Desktop
😼  $ cd testing-workshop/
/Users/kdodds/Desktop/testing-workshop
~/Desktop/testing-workshop (master)
😼  $ npm run setup

> testing-workshop@2.0.0 setup /Users/kdodds/Desktop/testing-workshop
> node ./scripts/verify && node ./scripts/install && npm run validate && node ./scripts/autofill-feedback-email.js

🎉  Congrats! Your system is setup properly
You should be good to install and run things.
📦  Installing dependencies via npm install
🔑  starting install in /Users/kdodds/Desktop/testing-workshop
npm WARN deprecated hoek@5.0.4: This version is no longer maintained. Please upgrade to the latest version.

> node@8.14.0 preinstall /Users/kdodds/Desktop/testing-workshop/node_modules/node
> node installArchSpecificPackage

+ node-darwin-x64@8.14.0
added 1 package in 1.282s
found 0 vulnerabilities

npm WARN lifecycle The node binary used for scripts is /Users/kdodds/Desktop/testing-workshop/node_modules/.bin/node but npm is using /Users/kdodds/n/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

> fsevents@1.2.4 install /Users/kdodds/Desktop/testing-workshop/node_modules/fsevents
> node install

[fsevents] Success: "/Users/kdodds/Desktop/testing-workshop/node_modules/fsevents/lib/binding/Release/node-v57-darwin-x64/fse.node" already installed
Pass --update-binary to reinstall or --build-from-source to recompile

> husky@0.14.3 install /Users/kdodds/Desktop/testing-workshop/node_modules/husky
> node ./bin/install.js

husky
setting up Git hooks
done


> cypress@3.1.3 postinstall /Users/kdodds/Desktop/testing-workshop/node_modules/cypress
> node index.js --exec install

 ✔  Downloaded Cypress
 ✔  Unzipped Cypress
 ✔  Finished Installation /Users/kdodds/Library/Caches/Cypress/3.1.3
added 1348 packages from 632 contributors and audited 27723 packages in 75.224s
found 69 low severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details
🎉  finished installing dependencies in "/Users/kdodds/Desktop/testing-workshop"
🔑  starting install in /Users/kdodds/Desktop/testing-workshop/shared
added 16 packages from 11 contributors and audited 18 packages in 3.393s
found 0 vulnerabilities

🎉  finished installing dependencies in "/Users/kdodds/Desktop/testing-workshop/shared"
🔑  starting install in /Users/kdodds/Desktop/testing-workshop/server

> fsevents@1.2.4 install /Users/kdodds/Desktop/testing-workshop/server/node_modules/fsevents
> node install

[fsevents] Success: "/Users/kdodds/Desktop/testing-workshop/server/node_modules/fsevents/lib/binding/Release/node-v57-darwin-x64/fse.node" already installed
Pass --update-binary to reinstall or --build-from-source to recompile

> nodemon@1.18.7 postinstall /Users/kdodds/Desktop/testing-workshop/server/node_modules/nodemon
> node bin/postinstall || exit 0

Love nodemon? You can now support the project via the open collective:
 > https://opencollective.com/nodemon/donate

added 567 packages from 216 contributors and audited 6193 packages in 12.415s
found 0 vulnerabilities

🎉  finished installing dependencies in "/Users/kdodds/Desktop/testing-workshop/server"
🔑  starting install in /Users/kdodds/Desktop/testing-workshop/client
npm WARN deprecated browserslist@2.11.3: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
npm WARN deprecated browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.

> fsevents@1.2.4 install /Users/kdodds/Desktop/testing-workshop/client/node_modules/fsevents
> node install

[fsevents] Success: "/Users/kdodds/Desktop/testing-workshop/client/node_modules/fsevents/lib/binding/Release/node-v57-darwin-x64/fse.node" already installed
Pass --update-binary to reinstall or --build-from-source to recompile

> uglifyjs-webpack-plugin@0.4.6 postinstall /Users/kdodds/Desktop/testing-workshop/client/node_modules/uglifyjs-webpack-plugin
> node lib/post_install.js

added 1666 packages from 770 contributors and audited 14946 packages in 40.455s
found 1 high severity vulnerability
  run `npm audit fix` to fix them, or `npm audit` for details
🎉  finished installing dependencies in "/Users/kdodds/Desktop/testing-workshop/client"
🔑  starting install in /Users/kdodds/Desktop/testing-workshop/other/configuration/calculator

> fsevents@1.2.4 install /Users/kdodds/Desktop/testing-workshop/other/configuration/calculator/node_modules/fsevents
> node install

[fsevents] Success: "/Users/kdodds/Desktop/testing-workshop/other/configuration/calculator/node_modules/fsevents/lib/binding/Release/node-v57-darwin-x64/fse.node" already installed
Pass --update-binary to reinstall or --build-from-source to recompile
npm WARN calculator.solution@1.0.0 No description
npm WARN calculator.solution@1.0.0 No repository field.

added 772 packages from 412 contributors and audited 10181 packages in 20.997s
found 0 vulnerabilities

🎉  finished installing dependencies in "/Users/kdodds/Desktop/testing-workshop/other/configuration/calculator"
🔑  starting install in /Users/kdodds/Desktop/testing-workshop/other/configuration/calculator.solution
npm WARN deprecated hoek@5.0.4: This version is no longer maintained. Please upgrade to the latest version.

> fsevents@1.2.4 install /Users/kdodds/Desktop/testing-workshop/other/configuration/calculator.solution/node_modules/fsevents
> node install

[fsevents] Success: "/Users/kdodds/Desktop/testing-workshop/other/configuration/calculator.solution/node_modules/fsevents/lib/binding/Release/node-v57-darwin-x64/fse.node" already installed
Pass --update-binary to reinstall or --build-from-source to recompile

> cypress@3.1.3 postinstall /Users/kdodds/Desktop/testing-workshop/other/configuration/calculator.solution/node_modules/cypress
> node index.js --exec install

npm WARN ajv-keywords@3.2.0 requires a peer of ajv@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN calculator.solution@1.0.0 No description
npm WARN calculator.solution@1.0.0 No repository field.

added 1388 packages from 629 contributors and audited 28298 packages in 48.077s
found 0 vulnerabilities

🎉  finished installing dependencies in "/Users/kdodds/Desktop/testing-workshop/other/configuration/calculator.solution"
👍  all dependencies installed

> testing-workshop@2.0.0 validate /Users/kdodds/Desktop/testing-workshop
> concurrently --names "lint,test:run,test:e2e" --prefix "[{name}]" --prefix-colors "bgGreen.reset.bold,bgBlue.reset.bold,bgRed.reset.bold" "npm run lint --silent" "npm run test:run --silent" "npm run test:e2e:run --silent"

[test:e2e] [server] src/controllers/auth.js -> dist/controllers/auth.js
[test:e2e] [server] src/controllers/auth.todo.js -> dist/controllers/auth.todo.js
[test:e2e] [server] src/controllers/posts.js -> dist/controllers/posts.js
[test:e2e] [server] src/controllers/posts.todo.js -> dist/controllers/posts.todo.js
[test:e2e] [server] src/controllers/users.bug.todo.js -> dist/controllers/users.bug.todo.js
[test:e2e] [server] src/controllers/users.js -> dist/controllers/users.js
[test:e2e] [server] src/controllers/users.todo.js -> dist/controllers/users.todo.js
[test:e2e] [server] src/index.js -> dist/index.js
[test:e2e] [server] src/routes/auth.js -> dist/routes/auth.js
[test:e2e] [server] src/routes/index.js -> dist/routes/index.js
[test:e2e] [server] src/routes/posts.js -> dist/routes/posts.js
[test:e2e] [server] src/routes/users.js -> dist/routes/users.js
[test:e2e] [server] src/start.js -> dist/start.js
[test:e2e] [server] src/utils/auth.js -> dist/utils/auth.js
[test:e2e] [server] src/utils/db.js -> dist/utils/db.js
[test:e2e] [server] src/utils/gist.js -> dist/utils/gist.js
[test:e2e] [server] src/utils/myjson.js -> dist/utils/myjson.js
[test:e2e] [server] npm run build:server --silent exited with code 0
[test:e2e] [client] Creating an optimized production build...
[lint] npm run lint --silent exited with code 0
[test:run]  PASS   expect  other/jest-expect/__tests__/expect-assertions.js
[test:run]  PASS   server  server/src/controllers/__tests__/posts.js (10.901s)
[test:run]  PASS   server  server/src/controllers/__tests__/users.js (11.201s)
[test:run]  PASS   server  server/src/controllers/__tests__/auth.js (11.262s)
[test:run]  PASS   server  server/src/controllers/__tests__/users.bug.todo.js (11.297s)
[test:run]  PASS   server  server/src/controllers/__tests__/auth.todo.js (11.343s)
[test:run]  PASS   server  server/src/controllers/__tests__/posts.todo.js
[test:run]  PASS   server  server/src/routes/__tests__/users.bug.todo.js
[test:run]  PASS   client  client/src/components/__tests__/user.js (12.577s)
[test:run]  PASS   server  server/src/routes/__tests__/auth.js (8.545s)
[test:run]  PASS   client  client/src/__tests__/app.login.todo.js
[test:run]  PASS   mocks  other/whats-a-mock/__tests__/thumb-war.2.todo.js
[test:run]  PASS   client  client/src/components/__tests__/login.step-2.todo.js
[test:run]  PASS   server  server/src/utils/__tests__/db.posts.js
[test:run]  PASS   server  server/src/utils/__tests__/db.users.js
[test:run]  PASS   server  server/src/routes/__tests__/posts.js
[test:run]  PASS   server  server/src/routes/__tests__/users.js (5.897s)
[test:run]  PASS   server  server/src/utils/__tests__/auth.todo.js
[test:run]  PASS   client  client/src/__tests__/app.create-post.js (8.849s)
[test:run]  PASS   server  server/src/utils/__tests__/auth.js
[test:run]  PASS   client  client/src/__tests__/app.register.js (7.889s)
[test:run]  PASS   client  client/src/components/__tests__/login.step-3.todo.js
[test:run]  PASS   client  client/src/components/__tests__/login.step-1.todo.js
[test:run]  PASS   mocks  other/whats-a-mock/__tests__/thumb-war.3.todo.js
[test:run]  PASS   client  client/src/__tests__/app.register.todo.js
[test:run]  PASS   client  client/src/components/__tests__/login.step-1.js
[test:run]  PASS   mocks  other/whats-a-mock/__tests__/thumb-war.1.todo.js
[test:run]  PASS   client  client/src/screens/__tests__/editor.js
[test:run]  PASS   mocks  other/whats-a-mock/__tests__/thumb-war.4.todo.js
[test:run]  PASS   client  client/src/__tests__/app.login.js (7.11s)
[test:run]  PASS   server  server/src/utils/__tests__/gist.js
[test:run]  PASS   mocks  other/whats-a-mock/__tests__/thumb-war.5.todo.js
[test:run]  PASS   server  server/src/utils/__tests__/myjson.js
[test:run]  PASS   mocks  other/whats-a-mock/__tests__/thumb-war.2.js
[test:run]  PASS   mocks  other/whats-a-mock/__tests__/thumb-war.4.js
[test:run]  PASS   mocks  other/whats-a-mock/__tests__/thumb-war.3.js
[test:run]  PASS   mocks  other/whats-a-mock/__tests__/thumb-war.5.js
[test:run]  PASS   client  client/src/screens/__tests__/editor.todo.js
[test:run]  PASS   server  server/src/utils/__tests__/gist.todo.js
[test:run]  PASS   client  client/src/components/__tests__/login.final.js
[test:run]  PASS   mocks  other/whats-a-mock/__tests__/thumb-war.1.js
[test:run]  PASS   client  client/src/components/__tests__/login.step-2.js
[test:e2e] [client] Compiled successfully.
[test:e2e] [client] 
[test:e2e] [client] File sizes after gzip:
[test:e2e] [client] 
[test:e2e] [client]   65.44 KB  build/static/js/main.45d7fa44.js
[test:e2e] [client]   400 B     build/static/css/main.c10a4320.css
[test:e2e] [client] 
[test:e2e] [client] The project was built assuming it is hosted at the server root.
[test:e2e] [client] You can control this with the homepage field in your package.json.
[test:e2e] [client] For example, add this to build it for GitHub Pages:
[test:e2e] [client] 
[test:e2e] [client]   "homepage" : "http://myname.github.io/myapp",
[test:e2e] [client] 
[test:e2e] [client] The build folder is ready to be deployed.
[test:e2e] [client] You may serve it with a static server:
[test:e2e] [client] 
[test:e2e] [client]   npm install -g serve
[test:e2e] [client]   serve -s build
[test:e2e] [client] 
[test:e2e] [client] Find out more about deployment here:
[test:e2e] [client] 
[test:e2e] [client]   http://bit.ly/2vY88Kr
[test:e2e] [client] 
[test:e2e] [client] npm run build:client --silent exited with code 0
[test:run]  PASS   react  other/simple-react/__tests__/item-list.js
[test:run]  PASS   client  client/src/__tests__/app.snapshot.not-recommended.js (6.274s)
[test:e2e] starting server using command "npm run start:core"
[test:e2e] and when url "http://localhost:8001" is responding
[test:e2e] running tests using command "cy:run"
[test:run]  PASS   calculator  other/configuration/calculator.solution/src/__tests__/utils.js
[test:run]  PASS   calculator  other/configuration/calculator.solution/src/__tests__/auto-scaling-text.js
[test:run]  PASS   calculator  other/configuration/calculator.solution/src/__tests__/calculator.js
[test:e2e] [client] UPDATE AVAILABLE The latest version of `serve` is 10.1.1
[test:e2e] [client] ERROR: DNS lookup failed: getaddrinfo ENOTFOUND LM-SJN-21001464
[test:e2e] [client] INFO: Accepting connections at http://localhost:8001
[test:e2e] [server] Listening on port 3001
[test:run] ---------------------------------------------|----------|----------|----------|----------|-------------------|
[test:run] File                                         |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
[test:run] ---------------------------------------------|----------|----------|----------|----------|-------------------|
[test:run] All files                                    |    35.62 |    34.66 |    40.34 |    35.18 |                   |
[test:run]  client/src                                  |        0 |        0 |        0 |        0 |                   |
[test:run]   app.js                                     |        0 |        0 |        0 |        0 |... 35,192,199,205 |
[test:run]   index.js                                   |        0 |        0 |      100 |        0 |... ,4,6,8,9,11,14 |
[test:run]  client/src/components                       |       34 |      100 |    57.89 |    35.42 |                   |
[test:run]   form.js                                    |        0 |      100 |        0 |        0 |... ,8,10,25,36,37 |
[test:run]   inputs.js                                  |        0 |      100 |      100 |        0 |         1,3,20,39 |
[test:run]   loading.js                                 |        0 |      100 |        0 |        0 |    1,2,4,15,19,38 |
[test:run]   login.js                                   |        0 |      100 |        0 |        0 |1,2,3,6,9,10,11,12 |
[test:run]   user.js                                    |       85 |      100 |    78.57 |       85 |          18,27,36 |
[test:run]  client/src/screens                          |        0 |        0 |        0 |        0 |                   |
[test:run]   editor.js                                  |        0 |      100 |        0 |        0 |... 13,16,20,21,25 |
[test:run]   editor.todo.js                             |        0 |      100 |        0 |        0 |... 10,13,17,18,22 |
[test:run]   home.js                                    |        0 |        0 |        0 |        0 |... 96,105,113,121 |
[test:run]  client/src/utils                            |        0 |        0 |        0 |        0 |                   |
[test:run]   api.js                                     |        0 |        0 |        0 |        0 |... 60,64,65,73,74 |
[test:run]  other/configuration/calculator.solution/src |        0 |        0 |        0 |        0 |                   |
[test:run]   auto-scaling-text.js                       |        0 |        0 |        0 |        0 |... 24,28,29,31,35 |
[test:run]   calculator-display.js                      |        0 |      100 |      100 |        0 |  1,2,3,4,7,8,9,11 |
[test:run]   calculator.js                              |        0 |        0 |        0 |        0 |... 99,305,311,317 |
[test:run]   index.js                                   |        0 |      100 |      100 |        0 |         1,2,3,4,6 |
[test:run]   utils.js                                   |        0 |        0 |        0 |        0 |    1,2,8,10,11,13 |
[test:run]  server/src                                  |    68.18 |       10 |      100 |    68.18 |                   |
[test:run]   index.js                                   |        0 |        0 |      100 |        0 |    1,2,4,5,6,8,10 |
[test:run]   start.js                                   |      100 |       25 |      100 |      100 |             11,12 |
[test:run]  server/src/controllers                      |    63.78 |       60 |    72.09 |    63.13 |                   |
[test:run]   auth.js                                    |      100 |      100 |      100 |      100 |                   |
[test:run]   auth.todo.js                               |    96.55 |    93.75 |      100 |     96.3 |                64 |
[test:run]   posts.js                                   |    81.25 |    72.73 |      100 |    81.25 |  8,17,35,42,45,52 |
[test:run]   posts.todo.js                              |        0 |        0 |        0 |        0 |... 45,47,48,49,52 |
[test:run]   users.bug.todo.js                          |    58.33 |    59.09 |       60 |    58.33 |... 18,20,37,43,49 |
[test:run]   users.js                                   |       84 |    81.82 |      100 |    83.33 |        8,17,40,46 |
[test:run]   users.todo.js                              |        0 |        0 |        0 |        0 |... 40,42,43,44,46 |
[test:run]  server/src/routes                           |      100 |      100 |      100 |      100 |                   |
[test:run]   auth.js                                    |      100 |      100 |      100 |      100 |                   |
[test:run]   index.js                                   |      100 |      100 |      100 |      100 |                   |
[test:run]   posts.js                                   |      100 |      100 |      100 |      100 |                   |
[test:run]   users.js                                   |      100 |      100 |      100 |      100 |                   |
[test:run]  server/src/utils                            |    95.45 |    72.73 |    95.24 |    94.87 |                   |
[test:run]   auth.js                                    |    81.82 |    57.14 |       80 |       80 |             28,44 |
[test:run]   db.js                                      |      100 |      100 |      100 |      100 |                   |
[test:run]   gist.js                                    |      100 |      100 |      100 |      100 |                   |
[test:run]   myjson.js                                  |      100 |      100 |      100 |      100 |                   |
[test:run] ---------------------------------------------|----------|----------|----------|----------|-------------------|
[test:run] 
[test:run] Test Suites: 5 skipped, 47 passed, 47 of 52 total
[test:run] Tests:       14 skipped, 119 passed, 133 total
[test:run] Snapshots:   25 passed, 25 total
[test:run] Time:        40.705s
[test:run] Ran all test suites in 6 projects.
[test:run] npm run test:run --silent exited with code 0
[test:e2e] 
[test:e2e] ====================================================================================================
[test:e2e] 
[test:e2e]   (Run Starting)
[test:e2e] 
[test:e2e]   ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
[test:e2e]   │ Cypress:    3.1.3                                                                              │
[test:e2e]   │ Browser:    Electron 59 (headless)                                                             │
[test:e2e]   │ Specs:      5 found (auth.login.js, auth.login.todo.js, auth.register.js, auth.register.todo.... │
[test:e2e]   └────────────────────────────────────────────────────────────────────────────────────────────────┘
[test:e2e] 
[test:e2e] 
[test:e2e] ────────────────────────────────────────────────────────────────────────────────────────────────────
[test:e2e]                                                                                                     
[test:e2e]   Running: auth.login.js...                                                                (1 of 5) 
[test:e2e] 
[test:e2e] 
[test:e2e]   authentication
    ✓ should allow existing users to login (5224ms)
[test:e2e] 
[test:e2e] 
[test:e2e]   1 passing (5s)
[test:e2e] 
[test:e2e] 
[test:e2e]   (Results)
[test:e2e] 
[test:e2e]   ┌─────────────────────────────┐
[test:e2e]   │ Tests:        1             │
[test:e2e]   │ Passing:      1             │
[test:e2e]   │ Failing:      0             │
[test:e2e]   │ Pending:      0             │
[test:e2e]   │ Skipped:      0             │
[test:e2e]   │ Screenshots:  0             │
[test:e2e]   │ Video:        true          │
[test:e2e]   │ Duration:     5 seconds     │
[test:e2e]   │ Spec Ran:     auth.login.js │
[test:e2e]   └─────────────────────────────┘
[test:e2e] 
[test:e2e] 
[test:e2e]   (Video)
[test:e2e] 
[test:e2e]   - Started processing:   Compressing to 32 CRF
[test:e2e]   - Finished processing:  /Users/kdodds/Desktop/testing-workshop/cypress/videos/auth.login.js.mp4 (1 second)
[test:e2e] 
[test:e2e] 
[test:e2e] ────────────────────────────────────────────────────────────────────────────────────────────────────
[test:e2e]                                                                                                     
[test:e2e]   Running: auth.login.todo.js...                                                           (2 of 5) 
[test:e2e] 
[test:e2e] 
[test:e2e]   authentication
    ✓ should allow existing users to login (99ms)
[test:e2e]     - I submitted my elaboration and feedback
[test:e2e] 
[test:e2e] 
[test:e2e]   1 passing (161ms)
[test:e2e]   1 pending
[test:e2e] 
[test:e2e] 
[test:e2e]   (Results)
[test:e2e] 
[test:e2e]   ┌──────────────────────────────────┐
[test:e2e]   │ Tests:        2                  │
[test:e2e]   │ Passing:      1                  │
[test:e2e]   │ Failing:      0                  │
[test:e2e]   │ Pending:      1                  │
[test:e2e]   │ Skipped:      0                  │
[test:e2e]   │ Screenshots:  0                  │
[test:e2e]   │ Video:        true               │
[test:e2e]   │ Duration:     0 seconds          │
[test:e2e]   │ Spec Ran:     auth.login.todo.js │
[test:e2e]   └──────────────────────────────────┘
[test:e2e] 
[test:e2e] 
[test:e2e]   (Video)
[test:e2e] 
[test:e2e]   - Started processing:   Compressing to 32 CRF
[test:e2e]   - Finished processing:  /Users/kdodds/Desktop/testing-workshop/cypress/videos/auth.login.todo.js.mp4 (0 seconds)
[test:e2e] 
[test:e2e] 
[test:e2e] ────────────────────────────────────────────────────────────────────────────────────────────────────
[test:e2e]                                                                                                     
[test:e2e]   Running: auth.register.js...                                                             (3 of 5) 
[test:e2e] 
[test:e2e] 
[test:e2e]   authentication
    ✓ should allow users to register (2536ms)
[test:e2e] 
[test:e2e] 
[test:e2e]   1 passing (3s)
[test:e2e] 
[test:e2e] 
[test:e2e]   (Results)
[test:e2e] 
[test:e2e]   ┌────────────────────────────────┐
[test:e2e]   │ Tests:        1                │
[test:e2e]   │ Passing:      1                │
[test:e2e]   │ Failing:      0                │
[test:e2e]   │ Pending:      0                │
[test:e2e]   │ Skipped:      0                │
[test:e2e]   │ Screenshots:  0                │
[test:e2e]   │ Video:        true             │
[test:e2e]   │ Duration:     2 seconds        │
[test:e2e]   │ Spec Ran:     auth.register.js │
[test:e2e]   └────────────────────────────────┘
[test:e2e] 
[test:e2e] 
[test:e2e]   (Video)
[test:e2e] 
[test:e2e]   - Started processing:   Compressing to 32 CRF
[test:e2e]   - Finished processing:  /Users/kdodds/Desktop/testing-workshop/cypress/videos/auth.register.js.mp4 (1 second)
[test:e2e] 
[test:e2e] 
[test:e2e] ────────────────────────────────────────────────────────────────────────────────────────────────────
[test:e2e]                                                                                                     
[test:e2e]   Running: auth.register.todo.js...                                                        (4 of 5) 
[test:e2e] 
[test:e2e] 
[test:e2e]   authentication
[test:e2e]     - I submitted my elaboration and feedback
[test:e2e] 
[test:e2e] 
[test:e2e]   0 passing (7ms)
[test:e2e]   1 pending
[test:e2e] 
[test:e2e] 
[test:e2e]   (Results)
[test:e2e] 
[test:e2e]   ┌─────────────────────────────────────┐
[test:e2e]   │ Tests:        1                     │
[test:e2e]   │ Passing:      0                     │
[test:e2e]   │ Failing:      0                     │
[test:e2e]   │ Pending:      1                     │
[test:e2e]   │ Skipped:      0                     │
[test:e2e]   │ Screenshots:  0                     │
[test:e2e]   │ Video:        true                  │
[test:e2e]   │ Duration:     0 seconds             │
[test:e2e]   │ Spec Ran:     auth.register.todo.js │
[test:e2e]   └─────────────────────────────────────┘
[test:e2e] 
[test:e2e] 
[test:e2e]   (Video)
[test:e2e] 
[test:e2e]   - Started processing:   Compressing to 32 CRF
[test:e2e]   - Finished processing:  /Users/kdodds/Desktop/testing-workshop/cypress/videos/auth.register.todo.js.mp4 (0 seconds)
[test:e2e] 
[test:e2e] 
[test:e2e] ────────────────────────────────────────────────────────────────────────────────────────────────────
[test:e2e]                                                                                                     
[test:e2e]   Running: posts.js...                                                                     (5 of 5) 
[test:e2e] 
[test:e2e] 
[test:e2e]   posts
    ✓ should allow existing users to login (3831ms)
[test:e2e] 
[test:e2e] 
[test:e2e]   1 passing (5s)
[test:e2e] 
[test:e2e] 
[test:e2e]   (Results)
[test:e2e] 
[test:e2e]   ┌─────────────────────────┐
[test:e2e]   │ Tests:        1         │
[test:e2e]   │ Passing:      1         │
[test:e2e]   │ Failing:      0         │
[test:e2e]   │ Pending:      0         │
[test:e2e]   │ Skipped:      0         │
[test:e2e]   │ Screenshots:  0         │
[test:e2e]   │ Video:        true      │
[test:e2e]   │ Duration:     3 seconds │
[test:e2e]   │ Spec Ran:     posts.js  │
[test:e2e]   └─────────────────────────┘
[test:e2e] 
[test:e2e] 
[test:e2e]   (Video)
[test:e2e] 
[test:e2e]   - Started processing:   Compressing to 32 CRF
[test:e2e]   - Finished processing:  /Users/kdodds/Desktop/testing-workshop/cypress/videos/posts.js.mp4 (2 seconds)
[test:e2e] 
[test:e2e] 
[test:e2e] ====================================================================================================
[test:e2e] 
[test:e2e]   (Run Finished)
[test:e2e] 
[test:e2e] 
[test:e2e]       Spec                                                Tests  Passing  Failing  Pending  Skipped 
[test:e2e]   ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
[test:e2e]   │ ✔ auth.login.js                             00:05        1        1        -        -        - │
[test:e2e]   ├────────────────────────────────────────────────────────────────────────────────────────────────┤
[test:e2e]   │ ✔ auth.login.todo.js                        157ms        2        1        -        1        - │
[test:e2e]   ├────────────────────────────────────────────────────────────────────────────────────────────────┤
[test:e2e]   │ ✔ auth.register.js                          00:02        1        1        -        -        - │
[test:e2e]   ├────────────────────────────────────────────────────────────────────────────────────────────────┤
[test:e2e]   │ ✔ auth.register.todo.js                      20ms        1        -        -        1        - │
[test:e2e]   ├────────────────────────────────────────────────────────────────────────────────────────────────┤
[test:e2e]   │ ✔ posts.js                                  00:03        1        1        -        -        - │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘
[test:e2e]     All specs passed!                           00:11        6        4        -        2        -  
[test:e2e] 
[test:e2e] [client] 
[test:e2e] [client] INFO: Gracefully shutting down. Please wait...
[test:e2e] [server] npm run start:server --silent exited with code 0
[test:e2e] [client] npm run start:client --silent exited with code 0
[test:e2e] npm run test:e2e:run --silent exited with code 0
? what's your email address? 

prompt timed out. No worries. Run `node ./scripts/autofill-feedback-email.js` if you'd like to try again
~/Desktop/testing-workshop (master)
😼  $ 
```

Sorry :-/

**Comment by iwakoscott** [comment]
That's ok so it seems like it is just a problem that I am having so that gives me hope. I will keep playing around with it. Thanks, Kent! Happy Holidays!

**Comment by kentcdodds** [comment]
Same to you! And good luck 💯
